apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 851725313788.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 851725313788.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: ada74c0e
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
